// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS7qwi7Qog09NCtEhOnpuxuRmn6m5mXpg',
    appId: '1:313973819099:web:e2743731842e44609baefe',
    messagingSenderId: '313973819099',
    projectId: 'chattapp-f5184',
    authDomain: 'chattapp-f5184.firebaseapp.com',
    storageBucket: 'chattapp-f5184.firebasestorage.app',
    measurementId: 'G-71YHM7XT83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI22sacbqH68svgIzkedbr2XnStU_cMhI',
    appId: '1:313973819099:android:85c6e1e93f54b8879baefe',
    messagingSenderId: '313973819099',
    projectId: 'chattapp-f5184',
    storageBucket: 'chattapp-f5184.firebasestorage.app',
  );
}
